### ISSUE TITLE
[pix_chroma_key]: Linux OK, same patch on Mac failed

### ISSUE THREAD

**Issue by jamshark70** [umlaeute/Gem#282] opened 2021-11-18 10:29 UTC
With the pictured patch, Linux correctly renders the green background of the video transparent, but when I took it into the classroom (Mac lab) -- no transparency, with an identical patch and video file. (Perhaps not an identical Gem version... under time pressure, I'm afraid I didn't check.)

I can imagine two possible explanations (not ruling out others):

1. Perhaps the Linux codec is serving up RGBA while the Mac codec gave YUV by default.
2. Or perhaps it's a bug that manifests in Mac only.

Any ideas?

Oh, curiously, in Linux I had to set "direction 1" for the *left* image to be treated as the key source (though the help patch suggests otherwise). In Mac, neither direction 0 or 1 got the right result.

![pd-chromakey-2](https://user-images.githubusercontent.com/318301/142398228-0e296c85-3c23-4248-a935-0083c4e5d18e.png)

**Comment by Ant1r** [comment] 2021-11-18 11:05
I think you should try adding an [alpha] in your chain, for example just before the [rectangle].

**Comment by umlaeute** [comment] 2021-11-18 12:30
> Perhaps the Linux codec is serving up RGBA while the Mac codec gave YUV by default.

this.

add a `[pix_rgba]` before the `[pix_chroma_key]`. or use the `[colorspace(` message to `[pix_film].
or use both (`[pix_rgba]` won't do anything if the colorspace is already RGBA).

the philosophy is: if a specific colorspace is required, add code that ensures that it is. the default colorspace might target optimized playback rather than compatibility.

i'm closing this as intended behaviour  (i don't want to make YUV the default colorspace; and Mac people have always been very verbose that this is the only sane colorspace form them)

**Closed by umlaeute** 2021-11-18 12:30 UTC

**Comment by jamshark70** [comment] 2021-11-18 23:52
I see... unfortunately, I didn't think of this until after the fact (one isn't optimally clearheaded when one has five minutes before the start of class, and the patch didn't work, and there are 40 students sitting there waiting).

I do think, however, that the philosophy should be documented. There is no hint in either [pix_film] or [pix_chroma_key] help that, for the same patch, the color space may vary by OS.

I can go ahead and do a quick PR for that -- just noting that, while it may be intended behavior, it's also currently undocumented behavior.

**Comment by umlaeute** [comment] 2021-11-19 20:27
i agree that this should be documented :-)
