### ISSUE TITLE
clip planes of [gemwin] does not affects objects in [ortho] mode

### ISSUE THREAD

**Issue by kubriel** [umlaeute/Gem#115] opened 2016-06-28 16:02 UTC
it is debian package of Gem, so maybe it irrelevant.
GEM: ver: 0.93.3
make big object with [ortho] and change far plane with `[perspec -1 1 -1 1 1 $1(` to gemwin.
to see results `[draw line(` is nice.

everything work as expected without ortho mode.

**Comment by umlaeute** [comment] 2016-06-29 07:54
please do provide an example patch.

(also don't be afraid: the problem is very unlikely to be Debian-specific, so this tracker is the very place to report it)

**Comment by umlaeute** [comment] 2018-12-19 19:43
this is hardcoded behaviour which is unlikely to change ever (so I'm going to close this).

you can build your own `[ortho]` variant with `[GEMglOrtho]` (which takes similar parameters as the `[perspec(` message).

**Closed by umlaeute** 2018-12-19 19:43 UTC
