### ISSUE TITLE
[text3d] freezes pd on Linux

### ISSUE THREAD

**Issue by mxa** [umlaeute/Gem#191] opened 2018-08-15 19:07 UTC
GEM: Graphics Environment for Multimedia
GEM: ver: 0.93.3 
GEM: compiled on 2018/02/01 at 21:58:19 UTC

attached patch freezes pd (Pd 0.48.1 or .2) after closing the gemwin.

[crashtest.pd.txt](https://github.com/umlaeute/Gem/files/2291371/crashtest.pd.txt)

**Comment by umlaeute** [comment] 2018-08-16 07:48
unreproducible (with the stock Debian/unstable package (`1:0.93.3-16`), which has the same version but has been compiled later).

what's your distribution, kernel, graphics-card (+driver)

**Comment by mxa** [comment] 2018-08-16 10:18
ubuntu 18.04.1 LTS
4.17.13-041713-lowlatency
VGA compatible controller [0300]: Intel Corporation 4th Gen Core Processor Integrated Graphics 
        Subsystem: Lenovo 4th Gen Core Processor Integrated Graphics Controller [17aa:502a]
        Kernel driver in use: i915

(haven't managed to get the nvidia running since moving from mint to ubuntu

**Comment by mxa** [comment] 2018-08-17 08:35
Installed NVIDIA prorietary drivers 390 and it seems to work as expected now.
Patches without the [text3d] are running fine with nouveau or the intel card though.

**Comment by mxa** [comment] 2018-09-25 12:30
I now have nvidia-390 but still the freezing. Trying to see if this also occurs on a newer compiled GEM.

**Comment by umlaeute** [comment] 2018-09-25 13:27
tried with my new GTX-1080, using both `nouveau` and `nvidia` (390.87-2; as provided by Debian) and everything works as expected (using both self-compiled `Gem-0.93.git3550ede3` and Debian's `Gem-0.93.3-16`)

**Comment by umlaeute** [comment] 2018-09-25 13:29
note: that i'm using a stock-kernel (`4.18.0-1-amd64`) and XFce4 as my window-manager without any compositing effects.

**Comment by mxa** [comment] 2018-09-25 13:36
Just tested it with Gem from Git and it works there.

**Comment by mxa** [comment] 2018-11-30 10:33
My assessment was wrong that it has to do with compiling Gem from Git. Actually I fixed my driver for NVIDIA at the same time. So this bug is there when using the intel card, but not there when using NVIDIA. Wether you use the repository or git version of Gem doesn't matter.

**Comment by claudeha** [comment] 2019-01-17 22:14
Can't reproduce on Debian Buster with `amdgpu` driver and `gemglxwindow`:

    GEM: ver: 0.94.git v0.94_pre1-145-ge879bff2

**Comment by mxa** [comment] 2019-01-18 21:53
I assume it only affects intel GPUs, not NVIDIA or amd

**Comment by umlaeute** [comment] 2019-01-18 21:57
btw, I'm using an intel card (on my laptop), and don't have any issues either:

~~~
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02) (prog-if 00 [VGA controller])
	Subsystem: Lenovo HD Graphics 620
	Kernel driver in use: i915
	Kernel modules: i915
~~~

**Comment by mxa** [comment] 2019-01-18 22:00
I might install buster next week so I can test it there. You haven't replied to my question on the list what the recommended install method for the Gem pre-release is for Cosmic users...

**Comment by umlaeute** [comment] 2023-12-20 14:13
i've tested again, with:
- Debian/trixie+sid amd64; "Intel TigerLake-LP GT2 [Iris Xe Graphics]"
- Debian trixie/sid amd64; "nVidia TU117GL [T400 4GB]"
- macOS Ventura (13.6.1) arm64; "Apple M1 Max"

on the two Debian machines, i've tested with Gem from the Debian repository (0.94-8+b2) and a recent snapshot (v0.94-726-ge49b7724e); on the macOS box i've tested with a recent snapshot (v0.94-727-g4afc5c70b)

I don't see a problem with your crashpatch on any of these systems.
i'm therefore closing this as "unreproducible"

**Closed by umlaeute** 2023-12-20 14:13 UTC
Labels: type:bug, help wanted
