### ISSUE TITLE
unable to switch to current window (do you have one?), cannot render! - Error Message

### ISSUE THREAD

**Issue by csunflowert** [umlaeute/Gem#271] opened 2021-01-07 12:20 UTC
Hi! I'm fairly new to Pure Data so forgive me for being dumb! I have a Mac, and am running on macOS Big Sur (recent update). Ever since this update, I have received the following messages in my PD window when trying to open a Gem window -  

[gemmacoswindow]: failed to init GLEW: your system only supports openGL-1.0
[gemmacoswindow]: unable to switch to current window (do you have one?), cannot render!

Is there a way to fix this? Thanks!

**Comment by umlaeute** [comment] 2021-01-07 15:58
this is a duplicate of #257 which also as suggestions on how to work around this issue

**Closed by umlaeute** 2021-01-07 15:58 UTC
