### ISSUE TITLE
size problem with [gemglfw3window]

### ISSUE THREAD

**Issue by H-MLim** [umlaeute/Gem#285] opened 2021-12-10 18:01 UTC
<img width="844" alt="스크린샷 2021-12-11 02 55 50" src="https://user-images.githubusercontent.com/68152553/145619992-48bdc8c4-51d2-489e-adae-6b0ce40b3f59.png">

[test.pd.zip](https://github.com/umlaeute/Gem/files/7694584/test.pd.zip)

after I got a problem and still not solved with [gemglutwindow], I tried to change default window with [gemglfw3window] but I'm afraid there are another issue with it. when I make a shape or texture, like [square], the shape size won't be matched with an actual window size. even when I tried to enlarge the arguments of [square] or via [dimen(. (as far as I know, like [square 4 4] is a maximum argument right?) what should I do for fix this? as same as before, I'm using MacOS Monterey ver. 12.0.1, Pd ver 0.51.4, Gem ver 0.94

**Comment by umlaeute** [comment] 2021-12-10 20:31
hmm, weird.
i have no immediate answer for you, but it seems like Gem thinks the window is bigger than it already is.

can you change the window size (dragging a corner of the window)? (this is possible on Linux; i cannot test on macOS right now). if so does that help (or change something)?

sidenote: what is the second argument of `[square 4 4]` supposed to do? :-)

**Comment by H-MLim** [comment] 2021-12-11 12:13
thank you. but still not solved while dragging windows. maybe problem of resolution? don't know yet.

btw, oh don't mind about the second argument. just forced habit. but anyway still same things are happened in [rectangle] or other shapes.

**Comment by 60-hz** [comment] 2021-12-13 17:22
I had this problem also a few weeks ago. I had to multiply the [GEMglViewport] dimension by 2 or so, the culprit might be a wrong Windows dimension returned by [gemglfw3window] under some OSX systems.

**Comment by umlaeute** [comment] 2022-03-01 10:44
this seems to be a duplicate of #243, so I'm closing this in favour of the older report.

**Closed by umlaeute** 2022-03-01 10:44 UTC

**Comment by skatzbizarro** [comment] 2022-07-03 18:10
> I had this problem also a few weeks ago. I had to multiply the [GEMglViewport] dimension by 2 or so, the culprit might be a wrong Windows dimension returned by [gemglfw3window] under some OSX systems.

how did you do that? i have the same issue and im trying this work around, trying to change the parameters send to the gemglviewport in the gemwin.pd, and reading the c++ class to see how it works. Any help i really appreciate it
