### ISSUE TITLE
fogmode message errors

### ISSUE THREAD

**Issue by 60-hz** [umlaeute/Gem#249] opened 2020-04-09 14:11 UTC
fogmode > 0 to a [gemwin] objet returns many "GL[1280]: invalid enumerant" to the console.

OSX 10.13.6
pd-0.50.2
GEM: ver: 0.94.git v0.94
GEM: compiled on Feb 12 2019

Tested in Ubuntu 18.04 and same error appears.

**Comment by umlaeute** [comment] 2020-09-21 13:09
does that happen with [examples/02.advanced/04.Fog.pd ](https://github.com/umlaeute/Gem/blob/master/examples/02.advanced/04.Fog.pd).

the example patch works for me ("Debian/sid amd64; GeForce GTX 1080" (nvidia-drivers), and "Debian/sid amd64; Intel HD Graphics 620")

**Comment by umlaeute** [comment] 2023-12-20 13:53
i've tested again, with:
- Debian/trixie+sid amd64; "Intel TigerLake-LP GT2 [Iris Xe Graphics]"
- Debian trixie/sid amd64; "nVidia TU117GL [T400 4GB]"
- macOS Ventura (13.6.1) arm64; "Apple M1 Max"

and i don't see any problem on any of these systems.
i'm therefore closing this as "unreproducible"

**Closed by umlaeute** 2023-12-20 13:53 UTC
Labels: state:unreproducible, category:openGL
