### ISSUE TITLE
NDI support?

### ISSUE THREAD

**Issue by newmediarecordings** [umlaeute/Gem#363] opened 2023-06-30 19:31 UTC
I have tried this on my m1 and intel macs, both same issue, and have also tried to update ndi, still an issue. I have tried to put the exact file in the Gem folder, still same. Can anyone help? 

Here is the prompt I'm given:

[GEM:recordNDI] Please (re)install the NewTek NDI Runtimes to use this plugin.
               need to find the library 'libndi.4.dylib'
               get it from http://new.tk/NDIRedistV4Apple
GEM: video record plugins: PNM
[GEM:videoNDI] Please (re)install the NewTek NDI Runtimes to use this plugin.
               need to find the library 'libndi.4.dylib'
               get it from http://new.tk/NDIRedistV4Apple
GEM: video capture plugins: AVF NDI decklink

**Comment by giulianobici** [comment] 2023-07-02 04:17
Hi @newmediarecordings 
I have the same issue on macbook Ventura 
2,3 GHz Dual-Core Intel Core i5
Intel Iris Plus Graphics 640 1536 MB
Macos Ventura 13.2.1 (22D68)

**Comment by umlaeute** [comment] 2023-07-03 06:13
i don't think (I've never tested this on anything but Linux) the `libndi.4.dylib` should be in the Gem folder, but instead in some system--wide folder, most likely in `/usr/local/lib/`.

alternatively set the `NDILIB_REDIST_FOLDER` envvar to the place where the `libndi.4.dylib` file is located and restart Gem (no, I have no clue  how to set envvars on macOS so they have an effect for applications started from the desktop).

it would probably be good to automatically set the `NDILIB_REDIST_FOLDER` (if it is not set explicitly by the user) to point to the Gem installation path...

**Comment by umlaeute** [comment] 2023-07-03 06:27
sidenote: I also noticed that NDI has obviously bumped the soname version to `5`, which probably indicates that the there's some API incompatibility...

**Comment by umlaeute** [comment] 2023-07-03 11:36
i just noticed, that (at least on Linux), it's indeed enough to copy the `libndi.so*` files besides the `gem_videoNDI.so` (or simply: the Gem-binary).

So the issue is most likely simply that the soname bump is responsible for not being able to use the NDI dylibs.

i'll push an update to the NDI SDK v5.

**Comment by umlaeute** [comment] 2023-07-03 13:41
Fixed with f17c966077b26020a1f27376b5eb25e057c67da7

**Closed by umlaeute** 2023-07-03 13:41 UTC
Labels: enhancement, category:documentation, OS:macOS, plugins:video
