### ISSUE TITLE
gem_imageTIFF crashes when disk is full

### ISSUE THREAD

**Issue by avilleret** [umlaeute/Gem#132] opened 2017-01-17 14:44 UTC

**Comment by umlaeute** [comment] 2017-01-18 09:11
when doing what?
(given the recent report of #133, i guess this is about writing images to a full disk).

also, could you provide a backtrace?

**Comment by avilleret** [comment] 2017-01-18 09:25
When saving TIFF file with ̀[pix_write]` I recorded this backtrace when the disk becomes full : https://gist.github.com/avilleret/1a1c39f1512140fe2a90b27883b039d5

**Comment by umlaeute** [comment] 2017-12-05 21:46
i'm not able to reproduce this.
instead i get nice error messages:
~~~
[GEM:imageTIFF] /tmp/ram/new00005.tif Error writing TIFF header
error: GEM: Unable to save image to '/tmp/ram/new00005.tif'
~~~

closing this now (please complain, if the problem persists)

**Closed by umlaeute** 2017-12-05 21:46 UTC
Labels: bug
