### ISSUE TITLE
[text3d]: unable to open xxx.ttf

### ISSUE THREAD

**Issue by jcp76300** [umlaeute/Gem#361] opened 2023-06-17 15:51 UTC
On a Raspberry Pi under RaspberryOS, I can't use any font, even vera.ttf !
Anybody had the same issue ? How to solve it ?

**Comment by umlaeute** [comment] 2023-06-17 17:57
try passing the full path to the font.

**Comment by jcp76300** [comment] 2023-06-18 04:55
[font /home/.local/.fonts/vera.ttf(
|
[text3d]

error : [text3d]: unable to open '/home/.local/.fonts/vera.ttf'

Even when I do
[openpanel]
|
[font $1]
|
[text3d]

same error, with any ttf or otf font at any path

**Comment by jcp76300** [comment] 2023-06-18 15:15
After research in the GEM source codes, it seems that it is in the TextBaseFTGL.cpp file at line 190 that the error occurs: m_font=makeFont(bufptr) would return NULL at line 191 and therefore the display of the error on line 192.
Can you confirm ?

**Comment by umlaeute** [comment] 2023-06-19 06:39
how did you obtain Gem? self-compiled or via your OS's package manager (`apt-get install gem`)?

You could also try building the demo applications that come with ftgl (`apt-get install libftgl-dev`), to see whether there's a fundamental problem with FTGL:

You can use the following makefile to build the examples in the `/usr/share/doc/libftgl-dev/examples/` directory (after copying the files to some writeable place, and uncompressing them)

```make
applications=c-demo simple
default: $(applications)

CFLAGS=$(shell pkg-config --cflags ftgl glut glu gl) -DHAVE_GL_GLUT_H=1
CXXFLAGS=$(shell pkg-config --cflags ftgl glut glu gl) -DHAVE_GL_GLUT_H=1
LDLIBS=$(shell pkg-config --libs ftgl glut glu gl) -lm

config.h:
	touch $@

$(applications): config.h

.PHONY: clean
clean:
	rm -f $(applications)
	rm -f config.h
```

**Comment by jcp76300** [comment] 2023-06-19 07:50
I got Gem via deken in Pd.
I've installed libftgl-dev yet, via apt-get.

**Comment by jcp76300** [comment] 2023-06-19 09:03
> You could also try building the demo applications that come with ftgl (`apt-get install libftgl-dev`), to see whether there's a fundamental problem with FTGL:
> 
> You can use the following makefile to build the examples in the `/usr/share/doc/libftgl-dev/examples/` directory (after copying the files to some writeable place, and uncompressing them)
> 
> ```makefile
> applications=c-demo simple
> default: $(applications)
> 
> CFLAGS=$(shell pkg-config --cflags ftgl glut glu gl) -DHAVE_GL_GLUT_H=1
> CXXFLAGS=$(CFLAGS)
> LDLIBS=$(shell pkg-config --libs ftgl glut glu gl) -lm
> 
> config.h:
> 	touch $@
> 
> $(applications): config.h
> 
> .PHONY: clean
> clean:
> 	rm -f $(applications)
> 	rm -f config.h
> ```
I did it and obtained the following errors : 
```typescript

jcp@raspberrypi:~/ftgl-dev $ make
touch config.h
Package glut was not found in the pkg-config search path.
Perhaps you should add the directory containing `glut.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glut' found
Package glut was not found in the pkg-config search path.
Perhaps you should add the directory containing `glut.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glut' found
cc  -DHAVE_GL_GLUT_H=1    c-demo.c config.h   -lm -o c-demo
cc1: fatal error: c-demo.c: Aucun fichier ou dossier de ce type
compilation terminated.
make: *** [<commande interne> : c-demo] Erreur 1

**Comment by umlaeute** [comment] 2023-06-19 11:58
well, `apt-get install libglut-dev libftgl-dev` to get all the dependencies...

**Comment by jcp76300** [comment] 2023-06-19 12:29
apt-get can't find libglut-dev

**Comment by jcp76300** [comment] 2023-06-19 12:36
I installed 
```
sudo apt-get freeglut3-dev libftgl-dev
```
and it answers they are already the most recent installed versions

**Comment by jcp76300** [comment] 2023-06-19 16:19
```
for p in ftgl glu gl; do pkg-config --libs $p; done
```
returns
```
-lftgl
-lGLU -lGL
-lGL
```

**Comment by umlaeute** [comment] 2023-06-19 16:20
well, then my [above modifications](https://github.com/umlaeute/Gem/issues/361#issuecomment-1597427423) to the makefile should allow you to compile and test the examples.

neverthless, do try the `apt`-provided package of Gem.

**Comment by jcp76300** [comment] 2023-06-19 16:43
It compiled successfully ! Greetings.

but after (/.fonts dir is in /home/jcp, not in home/.local)
```
./c-demo /home/jcp/.fonts/vera.ttf
```
answer is
```
./c-demo: couldn't load font /home/jcp/.fonts/vera.ttf
```

**Comment by umlaeute** [comment] 2023-06-19 18:50
> `./c-demo: couldn't load font /home/jcp/.fonts/vera.ttf`


Then I'm afraid the problem is a general FTGL problem, and needs to be fixed there.

You probably should file a bug against your distribution, something like

```sh
reportbug libftgl2
```

Since the problem is not actionable upon on our side, I'm closing this.
Good luck

**Closed** 2023-06-19 18:50 UTC
