### ISSUE TITLE
videoDECKLINK plugin code outdated

### ISSUE THREAD

**Issue by kubriel** [umlaeute/Gem#240] opened 2019-11-05 08:27 UTC
i tried to compile videoDECKLINK plugin with Blackmagic_DeckLink_SDK_11.3, but found some errors because of to API change i believe:

~~~gcc
videoDECKLINK.cpp: In member function ‘virtual bool gem::plugins::videoDECKLINK::open(gem::Properties&)’:
videoDECKLINK.cpp:453:5: error: ‘IDeckLinkAttributes’ was not declared in this scope
     IDeckLinkAttributes*dlAttribs=0;
     ^~~~~~~~~~~~~~~~~~~
videoDECKLINK.cpp:453:5: note: suggested alternative: ‘BMDDeckLinkAttributeID’
     IDeckLinkAttributes*dlAttribs=0;
     ^~~~~~~~~~~~~~~~~~~
     BMDDeckLinkAttributeID
videoDECKLINK.cpp:453:25: error: ‘dlAttribs’ was not declared in this scope
     IDeckLinkAttributes*dlAttribs=0;
                         ^~~~~~~~~
videoDECKLINK.cpp:455:38: error: ‘IID_IDeckLinkAttributes’ was not declared in this scope
     if (S_OK == m_dl->QueryInterface(IID_IDeckLinkAttributes,
                                      ^~~~~~~~~~~~~~~~~~~~~~~
videoDECKLINK.cpp:455:38: note: suggested alternative: ‘BMDDeckLinkAttributeID’
     if (S_OK == m_dl->QueryInterface(IID_IDeckLinkAttributes,
                                      ^~~~~~~~~~~~~~~~~~~~~~~
                                      BMDDeckLinkAttributeID
videoDECKLINK.cpp:469:3: error: ‘BMDDisplayModeSupport’ was not declared in this scope
   BMDDisplayModeSupport displayModeSupported;
   ^~~~~~~~~~~~~~~~~~~~~
videoDECKLINK.cpp:469:3: note: suggested alternative: ‘bmdDisplayModeSupports3D’
   BMDDisplayModeSupport displayModeSupported;
   ^~~~~~~~~~~~~~~~~~~~~
   bmdDisplayModeSupports3D
videoDECKLINK.cpp:474:10: error: ‘displayModeSupported’ was not declared in this scope
         &displayModeSupported,
          ^~~~~~~~~~~~~~~~~~~~
videoDECKLINK.cpp:474:10: note: suggested alternative: ‘bmdDisplayModeSupports3D’
         &displayModeSupported,
          ^~~~~~~~~~~~~~~~~~~~
          bmdDisplayModeSupports3D
videoDECKLINK.cpp:478:7: error: ‘displayModeSupported’ was not declared in this scope
   if (displayModeSupported == bmdDisplayModeNotSupported) {
       ^~~~~~~~~~~~~~~~~~~~
videoDECKLINK.cpp:478:7: note: suggested alternative: ‘bmdDisplayModeSupports3D’
   if (displayModeSupported == bmdDisplayModeNotSupported) {
       ^~~~~~~~~~~~~~~~~~~~
       bmdDisplayModeSupports3D
videoDECKLINK.cpp:478:31: error: ‘bmdDisplayModeNotSupported’ was not declared in this scope
   if (displayModeSupported == bmdDisplayModeNotSupported) {
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
videoDECKLINK.cpp:478:31: note: suggested alternative: ‘bmdDisplayModeSupports3D’
   if (displayModeSupported == bmdDisplayModeNotSupported) {
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
                               bmdDisplayModeSupports3D
make[1]: *** [Makefile:572: gem_videoDECKLINK_la-videoDECKLINK.lo] Error 1
make[1]: Leaving directory '/home/kubriel/Downloads/Gem/plugins/videoDECKLINK'
make: *** [Makefile:444: all] Error 2
~~~

note that 11.4 SDK was already released,
and with 10.9.5 it builds fine, but i never got a reasonable picture out of it.

we still can use gstreamer to route stream from decklink to v4l2loopback and read it with [pix_video], but i believe with this plugin it should be lower latency.

**Comment by umlaeute** [comment] 2019-11-05 09:06
the joys of "professional" APIs :-(

**Comment by kubriel** [comment] 2019-11-23 18:40
i sadly cannot get it work even with plugins/videoDECKLINK/SDK "imported DeckLink-SDK (10.8?) from gst-plugins-bad1.0"
this works `gst-launch-1.0 decklinkvideosrc mode=16 connection=2 video-format=3 ! videoconvert ! xvimagesink`

**Comment by umlaeute** [comment] 2019-12-04 14:12
the Pd-console printout doesn't look bad.
what does not work then?

**Comment by kubriel** [comment] 2019-12-04 16:42
i had feeling that plugin reports dimensions of video as 64x64 beause of this:
> info: proplist read height float 64
> info: proplist read width float 64
also because i can see that picture is something like static black texture which can be 64x64 with some random colorful pixels, mostly on the borders. i can take screenshot of it if it can help. was trying to set properties with subpatch from pix_video-help.pd but no visible change happened.

**Comment by umlaeute** [comment] 2019-12-05 13:53
i downloaded the new DecklinkSDK, updated the firmware on my "Mini Recorder", connected my laptop to the `HDMI`-input and started Gem (as shipped with Debian).

The card was detected properly, but - as you say - the capturing was only random pixels at 64x64.

However, setting the connection-type manually from *auto* to **HDMI** (`[set connection HDMI(`) fixed the problem, and i could capture the 2nd screen of my laptop onto my desktop.

(you might need to restart the capturing).

looking at the code, it seems that the default connection is hardcoded to `SDI` (rather than `auto` as the *connection* property suggests).
the *width* and *height* properties are initialized to default values, and will be updated once an image is captured.

**Comment by umlaeute** [comment] 2019-12-05 19:55
sidenote: when compiling yourself, just pass `--with-DeckLink=local` to configure to use some headers that are included with Gem ( rather than the ones from blackmagic, which broke compatibility...)

**Comment by kubriel** [comment] 2019-12-06 11:24
now i was testing debian buster shipped gem, and i dont have similar results. i have also "Mini Recorder" here. first time i start rendering i see 64x64 random stuff. second time i start it i get a white picture. and [set connection HDMI( or [set format 16( sended to pix_video doesnt affect nothing i can see. what is version of desktopvideo you are using? or it is irelevant?

**Comment by umlaeute** [comment] 2019-12-06 11:39
the sdk version should be irrelevant. iirc, i'm using DeckLink-11.4.



you do have an HDMI-stream connected?
and i don't know what "format 16" would do, but here the default ("auto") always worked nicely so far.

you could also play with requesting and explicit device (eg `[device 3(` to select the correct stream).

when playing around i noticed that i would get an image with the second instance of `[pix_video]` running simultaneously (as i opened the help patch while having a `[pix_video]` open

**Comment by kubriel** [comment] 2019-12-06 14:40
i meant dektopvideo package as it provides libDeckLinkAPI.so and kernel modules. so i upgraded 11.3 to 11.4 but without any visible change.
i allways check if hardware is working and im getting signal with 
> DISPLAY=:0 gst-launch-1.0 decklinkvideosrc mode=16 connection=2 video-format=3 ! videoconvert ! xvimagesink
and it is, as i can see my video.
in gst,  with 'mode' i can set if stream is supposed to be 1080i50 or 1080p60 or whatever, which i misunderstood for [format $1(
and about "[device $1(" for the first started render, device 0 is colorful 64x64, all other are white. and after switching render off and on is device 0 also white. i think i tried maybe all combinations of messages without luck. i think im missing something what is obvious to you. very strange to me is that when send "[enumProps(, pd console allways prints "info: proplist write connection symbol auto". this seems to me that im not able to write properties.

**Comment by umlaeute** [comment] 2019-12-06 15:27
>i meant dektopvideo package as it provides libDeckLinkAPI.so and kernel
>modules. 

yes, thats what i meant :-)


> so i upgraded 11.3 to 11.4 but without any visible change.

as i said, the exact version shouldn't matter.
Gem (with DeckLink=local) as used by the Debian package), builds against an older SDK - incidentally the same as Gstreamer...


>
>in gst,  with 'mode' i can set if stream is supposed to be 1080i50 or
>1080p60 or whatever, which i misunderstood for [format $1(

you were correct. gst's "mode" is the same as Gem's "format", although i prefer symbolic names like "1080p60" over numbers like "3".
iirc, you can send both...


> very strange to me is that when send "[enumProps(, pd console
>allways prints "info: proplist write connection symbol auto". this
>seems to me that im not able to write properties.


the problem is, that "connection" is a write-only property, so there's no way to query its current state. the "auto" you see is really just a placeholder...

**Comment by kubriel** [comment] 2019-12-06 15:59
i understand. everything seems ok, no error reported, im just not getting picture. i tried two desktop computers with debian, different HDMI sources to decklink, fresh git gem, debian stable gem, combinations of messages, running it with sudo or altering /dev/blackmagic/io0 permissions. all i can get is having picture in gstreamer. lost all ideas.

**Comment by yrostudio** [comment] 2020-01-13 22:54
i've got exactly the same issue on macosx Mojave, PD 0.50-2 and last GEM from deken. Blackmagic Intensity pro, component 1080i50, driver version 10.11.4 (also tried with 11.4.1)
The first image looks like colored dots, then white screen. I tried a lot of connection/format combination without any result.

**Comment by kubriel** [comment] 2020-04-16 16:33
i can see in BlackmagicDesktopVideoSetup that im switching inputs with `[set connection HDMI(` and `[set connection SDI(` but thats all

**Comment by umlaeute** [comment] 2020-09-21 13:13
@kubriel i've updated the Decklink code, so could you please try again with current git?

**Comment by kubriel** [comment] 2020-10-20 09:22
@umlaeute i found this after some time, sorry. i will check it soon, thanks!

**Comment by kubriel** [comment] 2020-10-21 10:55
no matter what i do(tried different versions of desktopvideo installed, or using different SDK), i allways get
`library loading returned: dlerror '/home/kubriel/Downloads/Gem/gem_videoDECKLINK.so: undefined symbol: CreateDeckLinkIteratorInstance'`
while loading Gem. should'nt decklink libraries appear here?
`ldd gem_videoDECKLINK.so 
	linux-vdso.so.1 (0x00007ffc96398000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007fa45550e000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fa455304000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007fa4550fe000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa4550f9000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa454edb000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa454d0e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa454b89000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa4549c8000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa4549ae000)
	libnvidia-tls.so.418.152.00 => /usr/lib/x86_64-linux-gnu/libnvidia-tls.so.418.152.00 (0x00007fa4547aa000)
	libnvidia-glcore.so.418.152.00 => /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.418.152.00 (0x00007fa452b36000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fa4529f5000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fa4527e1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa455882000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fa4527b7000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fa4525b3000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fa4523ad000)
	libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fa452393000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa452387000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa452366000)`

**Comment by kubriel** [comment] 2020-10-21 14:33
all i get is no errors, and white picture

**Comment by kubriel** [comment] 2020-10-21 16:17
i got it working!
with SDK included with Gem.
it seems that Gem is not able to properly recognize RGB format of HDMI input.
i set my HDMI input signal to YCbCr444 and it works!
but not allways we are able to control pixel format of incoming signal.

**Comment by umlaeute** [comment] 2020-10-21 18:46
>  but not allways we are able to control pixel format of incoming signal.

true.
but i wouldn't even know how to change the pixel format to do some tests.

**Comment by kubriel** [comment] 2020-10-21 19:59
> i wouldn't even know how to change the pixel format to do some tests.

with nvidia its easy, you will find it in monitor settings of nvidia-settings, and with raspberry pii should be also easy:
/boot/config.txt

```
 hdmi_pixel_encoding=0 default       (limited for CEA, full for DMT)
 hdmi_pixel_encoding=1 RGB limited   (16-235)
 hdmi_pixel_encoding=2 RGB full      ( 0-255)
 hdmi_pixel_encoding=3 YCbCr limited (16-235)
 hdmi_pixel_encoding=4 YCbCr limited ( 0-255)
```

on intel or amd gpu i dont know.

i tried to mess with videoDECKLINK.cpp on lines 189 and 430
189: , m_cfg_pixelFormat(bmdFormat8BitYUV)
 and 
430: BMDPixelFormat pixformat = bmdFormat8BitYUV;

trying yo put there relevant values i found in DeckLinkAPIModes.h
but without luck, decklink device was left inactive.

anyway.. i see that video latency is much lower compared to gst > v4l2loopback > pix_video
so it is great achievement for my projects, but without possibility of input RGB pixel format, usage is still quite limited..

**Comment by umlaeute** [comment] 2020-11-06 19:07
hmm. i think i managed to output RGB with my nvidia card, and everything worked nicely.
i haven't actually checked whether the received frames are indeed RGB.

my understanding was, that the Decklink SDK would automatically do the conversion from me (if so requested).

anyhow, this is mainly to let you know that you haven't been forgotten.

but - given that the original issue ("videoDECKLINK plugin code outdated") is no longer relevant i'm going to close this ticket.
would you mind opening a new one for the colorspace issue?

**Closed by umlaeute** 2020-11-06 19:07 UTC

**Comment by umlaeute** [comment] 2021-07-07 15:50
i finally got around a RPi4, and i tried all options, and all give me an image:

| boot/config.txt | result |
|--------------------|----------|
|hdmi_pixel_encoding=0 | OK |
|hdmi_pixel_encoding=1 | OK |
|hdmi_pixel_encoding=2 | OK |
|hdmi_pixel_encoding=3 | OK |
|hdmi_pixel_encoding=4 | OK |

i have no idea whether the frames are actually RGB or YUV.

however, running `gst-launch-1.0 decklinkvideosrc ! autovideosink` indicates that regardless of setting i get `format=(string)UYVY`.
also note that i cannot do `gst-launch-1.0 decklinkvideosrc video-format=8bit-argb ! autovideosink`, as it results in:

>     WARNING: from element /GstPipeline:pipeline0/GstDecklinkVideoSrc:decklinkvideosrc0: Signal lost
>     Additional debug info:
>     ../sys/decklink/gstdecklinkvideosrc.cpp(1194): gst_decklink_video_src_create (): /GstPipeline:pipeline0/GstDecklinkVideoSrc:decklinkvideosrc0:
>     No input source was detected - video frames invalid
>     Redistribute latency...
>     ERROR: from element /GstPipeline:pipeline0/GstDecklinkVideoSrc:decklinkvideosrc0: Internal data stream error.

**Comment by umlaeute** [comment] 2022-07-05 11:52
even more finally, i think i found the culprit why my *tests* are failing: my *DeckLink Mini Recorder* simply does not support RGBA.

running the `DeviceList` example from the SDK i get:
```
=============== DeckLink Mini Recorder ===============

Attribute list:
 Device Interface:                        PCI
 Device Persistent ID:                    99ab90e9
 Device Topological ID:                   430300
 Number of sub-devices:                   1
 Sub-device index:                        0
 Serial port present:                     No
 Number of audio channels:                16
 Input mode detection supported ?         Yes
 Duplex Mode:                             Simplex
 Internal keying supported ?              No
 External keying supported ?              No
 HDMI timecode support:                   None

Supported video input display modes:

Unspecified Connection input:
 525i59.94 NTSC                    	  720 x  486 	   29.97 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 625i50 PAL                        	  720 x  576 	      25 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 525p59.94 NTSC                    	  720 x  486 	 59.9401 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 625p50 PAL                        	  720 x  576 	      50 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 1080p23.98                        	 1920 x 1080 	  23.976 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 1080p24                           	 1920 x 1080 	      24 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 1080p25                           	 1920 x 1080 	      25 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 1080p29.97                        	 1920 x 1080 	   29.97 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 1080p30                           	 1920 x 1080 	      30 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 1080i50                           	 1920 x 1080 	      25 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 1080i59.94                        	 1920 x 1080 	   29.97 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 1080i60                           	 1920 x 1080 	      30 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 720p50                            	 1280 x  720 	      50 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 720p59.94                         	 1280 x  720 	 59.9401 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 720p60                            	 1280 x  720 	      60 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
```

otoh, the *DeckLink SDI 4K* does support both YUV and RGB.

```
=============== DeckLink SDI 4K ===============

Attribute list:
 Device Interface:                        PCI
 Device Persistent ID:                    1e56062b
 Device Topological ID:                   470400
 Number of sub-devices:                   1
 Sub-device index:                        0
 Serial port present:                     Yes
Could not query the serial port name attribute- result = 80000008
 Number of audio channels:                16
 Input mode detection supported ?         Yes
 Duplex Mode:                             Full
 Internal keying supported ?              Yes
 External keying supported ?              No
 HDMI timecode support:                   None

Supported video output display modes:

Unspecified Connection output:
 525i59.94 NTSC                    	  720 x  486 	   29.97 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 625i50 PAL                        	  720 x  576 	      25 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 1080p23.98                        	 1920 x 1080 	  23.976 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 1080p24                           	 1920 x 1080 	      24 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 1080p25                           	 1920 x 1080 	      25 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 1080p29.97                        	 1920 x 1080 	   29.97 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 1080p30                           	 1920 x 1080 	      30 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 1080p50                           	 1920 x 1080 	      50 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 1080p59.94                        	 1920 x 1080 	 59.9401 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 1080p60                           	 1920 x 1080 	      60 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 1080i50                           	 1920 x 1080 	      25 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 1080i59.94                        	 1920 x 1080 	   29.97 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 1080i60                           	 1920 x 1080 	      30 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 720p50                            	 1280 x  720 	      50 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 720p59.94                         	 1280 x  720 	 59.9401 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 720p60                            	 1280 x  720 	      60 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 2Kp23.98 DCI                      	 2048 x 1080 	  23.976 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 2Kp24 DCI                         	 2048 x 1080 	      24 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 2Kp25 DCI                         	 2048 x 1080 	      25 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 2160p23.98                        	 3840 x 2160 	  23.976 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 2160p24                           	 3840 x 2160 	      24 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 2160p25                           	 3840 x 2160 	      25 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 2160p29.97                        	 3840 x 2160 	   29.97 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 2160p30                           	 3840 x 2160 	      30 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 4Kp23.98 DCI                      	 4096 x 2160 	  23.976 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 4Kp24 DCI                         	 4096 x 2160 	      24 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 4Kp25 DCI                         	 4096 x 2160 	      25 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         

Supported video input display modes:

Unspecified Connection input:
 525i59.94 NTSC                    	  720 x  486 	   29.97 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 625i50 PAL                        	  720 x  576 	      25 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 1080p23.98                        	 1920 x 1080 	  23.976 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 1080p24                           	 1920 x 1080 	      24 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 1080p25                           	 1920 x 1080 	      25 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 1080p29.97                        	 1920 x 1080 	   29.97 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 1080p30                           	 1920 x 1080 	      30 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 1080p50                           	 1920 x 1080 	      50 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 1080p59.94                        	 1920 x 1080 	 59.9401 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 1080p60                           	 1920 x 1080 	      60 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 1080i50                           	 1920 x 1080 	      25 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 1080i59.94                        	 1920 x 1080 	   29.97 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 1080i60                           	 1920 x 1080 	      30 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 720p50                            	 1280 x  720 	      50 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 720p59.94                         	 1280 x  720 	 59.9401 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 720p60                            	 1280 x  720 	      60 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 2Kp23.98 DCI                      	 2048 x 1080 	  23.976 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 2Kp24 DCI                         	 2048 x 1080 	      24 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 2Kp25 DCI                         	 2048 x 1080 	      25 FPS	8-bit YUV      10-bit YUV     8-bit ARGB     8-bit BGRA     10-bit RGB     ------         ------         10-bit RGBXLE  10-bit RGBX    
 2160p23.98                        	 3840 x 2160 	  23.976 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 2160p24                           	 3840 x 2160 	      24 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 2160p25                           	 3840 x 2160 	      25 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 2160p29.97                        	 3840 x 2160 	   29.97 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 2160p30                           	 3840 x 2160 	      30 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 4Kp23.98 DCI                      	 4096 x 2160 	  23.976 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 4Kp24 DCI                         	 4096 x 2160 	      24 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
 4Kp25 DCI                         	 4096 x 2160 	      25 FPS	8-bit YUV      10-bit YUV     ------         ------         ------         ------         ------         ------         ------         
```
