### ISSUE TITLE
[gemmacoswindow]: unable to switch to current window (do you have one?), cannot render!

### ISSUE THREAD

**Issue by alainbonardi** [umlaeute/Gem#290] opened 2022-04-08 06:47 UTC
Hello, I have been using Gem without any problem, and now I get a series of following messages in the Pd Window as soon as I open a Pd patch containing Gem objects:
[gemmacoswindow]: unable to switch to current window (do you have one?), cannot render!
My Mac is running under MacOS 10.14.6 and I use Pd 0.52.1
Thanks in advance for your help
Best,
Alain

**Comment by umlaeute** [comment] 2022-04-12 20:29
looks very much like a duplicate of #271 resp #257

**Closed by umlaeute** 2022-04-12 20:29 UTC
