### ISSUE TITLE
cant render the cube help

### ISSUE THREAD

**Issue by VenDoty** [umlaeute/Gem#412] opened 2024-01-23 07:23 UTC
help the [cube] object doesn't work
![bvcccccccc](https://github.com/umlaeute/Gem/assets/157456443/0a0e9ddb-fb1e-4409-90c3-36444b77fc79)
pls help

i think i need to download the runtime?

**Comment by umlaeute** [comment] 2024-01-23 07:51
- you *are* rendering the `[cube]` help
- this seems to be a duplicate of one of the there two issues
  - https://github.com/umlaeute/Gem/issues/390
  - https://github.com/umlaeute/Gem/issues/243
  (more likely the first one)

both of these issues has been resolved, but you obviously need a recent version of Gem.
for future reference, please *always* provide the following information:
- which OS (and which OS version)?
- which CPU?
- which version of Pd?
- which exact version of Gem? (as stated in the Pd-console when Gem gets loaded)

**Closed by umlaeute** 2024-01-23 07:51 UTC

**Comment by umlaeute** [comment] 2024-01-23 07:52
i'm closing this for now as `duplicate`. if it is not a duplicate of the mentioned issues, please add the relevant information and i'm going to re-open it.
