### ISSUE TITLE
build fails with error: expected ';' after expression

### ISSUE THREAD

**Issue by megrimm** [umlaeute/Gem#288] opened 2022-03-19 16:57 UTC
assuming this is related to assimp issues and not gem. documented here:
https://github.com/assimp/assimp/issues/4374

~~~
In file included from modelASSIMP3.cpp:14:
In file included from ./modelASSIMP3.h:19:
In file included from /opt/homebrew/Cellar/assimp/5.2.2/include/assimp/scene.h:55:
/opt/homebrew/Cellar/assimp/5.2.2/include/assimp/mesh.h:910:81: error: expected ';' after expression
            mTextureCoordsNames = new aiString *[AI_MAX_NUMBER_OF_TEXTURECOORDS] {};
                                                                                ^
1 error generated.
make[2]: *** [gem_modelASSIMP3_la-modelASSIMP3.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
~~~

**Comment by umlaeute** [comment] 2022-03-22 09:54
i'm not sure whether this is indeed a dupe of https://github.com/assimp/assimp/issues/4374, but i agree that it is most likely a problem outside of Gem.

just to add a few data-points: what is your OS (version)?  which compiler (version) do you use?

~~~console
$ g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
~~~

**Comment by megrimm** [comment] 2022-03-22 21:28
```
macOS 12.2.1 
Apple clang version 13.1.6 (clang-1316.0.21.2)
Target: arm64-apple-darwin21.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by FrankyLin2** [comment] 2022-12-03 08:51
Using GCC 11.3 instead of clang maybe solve this problem, for me it works well.

**Comment by umlaeute** [comment] 2023-12-20 13:45
i've bumped into the same problem while building Gem with XCode14 (`Apple clang version 14.0.0 (clang-1400.0.29.102)`).

my hack for now (where i'm stuck with assimp-5.2) is to just patch the assimp sources:
```sh
sed \
   -e 's|^\([[:space:]]*mTextureCoordsNames = new aiString \*\[AI_MAX_NUMBER_OF_TEXTURECOORDS\]\) {};[[:space:]]*$|\1; for (size_t i=0; i<AI_MAX_NUMBER_OF_TEXTURECOORDS; ++i) {mTextureCoordsNames[i] = nullptr;}|' \
   -i.bak "$(brew --cellar)"/assimp-fat/5.2*/include/assimp/mesh.h
```

however, note that homebrew now ships with assimp-5.3.1, where this has been fixed, so it's no longer necessary.


the actual assimp bug is https://github.com/assimp/assimp/issues/5203

**Closed by umlaeute** 2023-12-20 13:45 UTC
Labels: category::build-system
